# k8s-websrv-danny.custom-message.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-websrv-danny-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-websrv-danny-custom
  template:
    metadata:
      labels:
        app: k8s-websrv-danny-custom
    spec:
      containers:
      - name: k8s-websrv-danny
        image: dfdemo/hello-kubernetes:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Danny just deployed this Version1 on K8s!!

